import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import {Button} from "@fluentui/react-button";
import path from "path";
import {promises as fs} from "fs";

export default function Home(props: any) {
  return (
    <>
      <Button appearance="primary">Get started</Button>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className={styles.main}>
        {props.json}
      </main>
    </>
  )
}

export async function getServerSideProps(context: any) {
  const jsonDirectory = path.join(process.cwd(), 'public')
  const json = await fs.readFile(path.join(jsonDirectory, '/articles.json'), 'utf-8')
  return {
    props: {json}
  }
}
