import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import {Button} from "@fluentui/react-button";

export default function Home() {
  return (
    <>
      <Button appearance="primary">Get started</Button>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className={styles.main}>

      </main>
    </>
  )
}
